In [74]:
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import numpy as np

In [195]:
x = Variable(torch.arange(10,14))
x

Variable containing:
 10
 11
 12
 13
[torch.FloatTensor of size 4]

In [196]:
edges_np = np.array([(0,3),(3,1),(1,2),(2,3)])
edges_np = np.concatenate([edges_np,edges_np[:,[1,0]]])

In [197]:
edges_np

array([[0, 3],
       [3, 1],
       [1, 2],
       [2, 3],
       [3, 0],
       [1, 3],
       [2, 1],
       [3, 2]])

In [198]:
edge_selector = np.array([np.where(edges_np[:,0] == i)[0] for i in range(4)])

In [199]:
edge_selector

array([array([0]), array([2, 5]), array([3, 6]), array([1, 4, 7])], dtype=object)

In [204]:
edges = torch.LongTensor(edges_np)

In [205]:
#add both directions
#edges = torch.cat([edges,edges[:,[1,0]]])

In [206]:
edges


    0     3
    3     1
    1     2
    2     3
    3     0
    1     3
    2     1
    3     2
[torch.LongTensor of size 8x2]

In [207]:
weights = Variable(torch.rand(edges_np.shape))

In [208]:
weights

Variable containing:
 0.1713  0.6979
 0.0987  0.2637
 0.7546  0.8510
 0.1303  0.9747
 0.8513  0.6719
 0.4304  0.2805
 0.6838  0.8696
 0.4973  0.2799
[torch.FloatTensor of size 8x2]

In [209]:
tocompute = torch.index_select(x, 0, edges.view(-1)).view(-1, 2)

In [210]:
tocompute

Variable containing:
   10    13
   13    11
   11    12
   12    13
   13    10
   11    13
   12    11
   13    12
[torch.FloatTensor of size 8x2]

In [211]:
conv = tocompute* weights

In [212]:
conv

Variable containing:
  1.7134   9.0727
  1.2834   2.9007
  8.3001  10.2123
  1.5632  12.6711
 11.0667   6.7194
  4.7348   3.6461
  8.2054   9.5659
  6.4646   3.3589
[torch.FloatTensor of size 8x2]

In [213]:
for i in edge_selector:
    print i
    new_x = torch.index_select(conv, 0, torch.LongTensor(i))
    print new_x.data.numpy()
    print torch.max(new_x).data.numpy()

[0]
[[ 1.7134105   9.07269096]]
[ 9.07269096]
[2 5]
[[  8.30011368  10.21228886]
 [  4.73482943   3.64605427]]
[ 10.21228886]
[3 6]
[[  1.56317544  12.67114258]
 [  8.20543957   9.56587505]]
[ 12.67114258]
[1 4 7]
[[  1.283355     2.90070152]
 [ 11.06669426   6.71936607]
 [  6.4645896    3.3589325 ]]
[ 11.06669426]


In [ ]:
filter(lambda p: 